In [1]:
import numpy as np

In [2]:
it=[3,6,7,11]

In [3]:
#create numpy array
n=np.array(it)

In [4]:
n

array([ 3,  6,  7, 11])

In [5]:
#find data type
type(n)

numpy.ndarray

In [6]:
n.shape

(4,)

In [7]:
p=np.array([1,2,3,4])
p

array([1, 2, 3, 4])

In [8]:
#can use set instead of list
setnp=np.array({6,4,3})
setnp

array({3, 4, 6}, dtype=object)

In [9]:
dic=np.array({'a':'apple','b':'banana'})
dic

array({'a': 'apple', 'b': 'banana'}, dtype=object)

In [10]:
#two dimensional array
twod=np.array([[1,2],[3,4]])
twod

array([[1, 2],
       [3, 4]])

In [11]:
#to verify dimensionality of array
twod.shape

(2, 2)

In [12]:
threed=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])
threed

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ -1,  -2,  -3,  -4],
        [ -5,  -6,  -7,  -8],
        [ -9, -10, -11, -12]]])

In [13]:
threed.shape

(2, 3, 4)

In [14]:
diff=np.array([[1,2],[3,4,5]])
diff

array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [15]:
difflist=np.array([list([1,2]),list([3,4,5])])
difflist

array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [16]:
typediff=np.array([1,2,'g'])
typediff

array(['1', '2', 'g'], dtype='<U11')

In [17]:
#size prints number of elements in array
typediff.size

3

In [18]:
#Python range
list(range(9,13))

[9, 10, 11, 12]

In [19]:
list(range(9,16,2))

[9, 11, 13, 15]

In [20]:
#numpy has arange. Provides array
np.arange(9,13)

array([ 9, 10, 11, 12])

In [21]:
#to find documentation use ?. eg:np.arange?

In [22]:
#arr=np.arange(40)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#product of parameters in reshape equal to arange parameter
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
#arr2 value also changed.
arr1=np.arange(40)
arr2=arr1.reshape(8,5)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [25]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [26]:
arr1[0]=1290
arr2

array([[1290,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [27]:
arr1 is arr2

False