# Tensorflow

<p> TensorFlow is the most popular and adopted free and open-source deep learning library. It was first developed and maintained by Google. It can be used for both research and production. </p>

## TensorFlow Benefits

1. Highly efficient
2. Cross-platform (works on IOS, Android, Unix, Windows, in the cloud, in the browser etc etc)
3. Calculates gradients automatically (this is truly useful for Neural Networks, where the analytical solution of gradients would be VERY tedious to derive).
4. Deep integration with the Keras library (Functional approach, as well as high-level wrapper)
<p>Keras won’t work if you need to make low-level changes to your model. For that, you need TensorFlow. Keras is a wrapping over Tensorflow</p>

## General Notebook Setup

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# the %matplotlib inline will make your plot outputs appear and be stored within the notebook i.e in same window
%matplotlib inline

# Hide warnings
import warnings
warnings.filterwarnings('ignore')

## Install Tensorflow

<p> TensorFlow 2.x supports eager execution by default, so you don't need a session and to evaluate operations / tensors in order to extract values. </p>

In [2]:
#!pip install tensorflow
# or for GPU version:
# !pip install tensorflow-gpu

## Import Tensorflow

In [3]:
# Canonical way of importing TensorFlow
import tensorflow as tf

## Tensorflow 2.0

In [4]:
# Check tf version, oftentimes tensorflow is not backwards compatible
tf.__version__

'2.3.0'

## Intro to Tensorflow

### Core Components

#### 1. Tensor
<p>A Tensor in TensorFlow is an N-dimensional array (just like Numpys array object). Tensors are multilinear maps from vector spaces to real numbers. Scalars, vectors and matrices are all tensors. The Tensor represents units of data in TensorFlow.

Numpy arrays or Pandas DataFrames sent to Tensorflow functions are automatically converted into TensorFlow tensors.</p>

#### 2. Operations/Ops
<p>TensorFlow operations or ops are units / edges / nodes of computation (e.g. matrix multiplication, addition, etc.)</p>

#### 3. Computation Graph
<p>The computational graph is is an optimized, compiled representation of the dataflow and the order of computations that are sent to an execution environment (for example during model training).

TensforFlow 2.x supports eager execution, but when we build a model and then train it TensorFlow can compile the model and optimize the executions as a computational graph object. This is done by decorating a function with @tf.function.

This computational graph is then sent to another instance / runtime environment (e.g. on a CPU or GPU) for execution. The results are sent back to us. This makes TensorFlow computations highly distributable and it also allows us to automatically evaluate all gradients in the computation nodes.</p>

<center><img src="images/tf_graph.png"></center>

<p>TensorFlow 2.x supports eager execution by default.</p>

In [5]:
tf.executing_eagerly()

True

In [6]:
a = tf.Variable(10)

In [7]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [8]:
b = tf.constant(10)

In [9]:
type(b)

tensorflow.python.framework.ops.EagerTensor

## Tensorboard Setup

<p> TensorBoard is a visualization toolkit from Tensorflow to display different metrics, parameters, and other visualizations that help debug, track, fine-tune, optimize, and share your deep learning experiment results.</p>
<p> TensorBoard used to monitor and analyze computational graphs etc. </p>

In [10]:
#from datetime import datetime
#import os
#import pathlib

# utcnow() : Return the current UTC date and time as datetime object
# strftime() : Convert object to a string according to a given format
#t = datetime.utcnow().strftime("%Y%m%d%H%M%S") 
#log_dir = "tf_logs"
#logd = "{}/r{}/".format(log_dir, t)

# Make directory if it doesn't exist
#from pathlib import Path
#home = str(os.getcwd())
# home = str(Path.home())

# os.sep() : Create a new string object from the given object.
#logdir = os.path.join(os.sep,home,logd)

#if not os.path.exists(logdir):
#    os.makedirs(logdir)
from datetime import datetime
import os
import pathlib

t = datetime.utcnow().strftime("%Y%m%d%H%M%S") 
log_dir = "tf_logs"
logd = "{}\\r{}\\".format(log_dir, t)

# Make directory if it doesn't exist

from pathlib import Path
home = str(Path.home())

logdir = os.path.join(os.sep,home,logd)

if not os.path.exists(logdir):
    os.makedirs(logdir)

## 1. Tensorflow tensors

### 1.1 tf.constant

<p>Constants are initialized directly and eager execution let's us see the values without creating a session and running the tensor.</p>

In [11]:
a = tf.constant(2)
b = tf.constant(5)

In [12]:
a # note the numpy value

<tf.Tensor: shape=(), dtype=int32, numpy=2>

<p>The .numpy() method will return the result as a numpy array.</p>

In [13]:
# Eager evaluation of tensors
a.numpy()

2

#### We can also perform operations on tensors

In [14]:
a * b

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [15]:
type(a*b)

tensorflow.python.framework.ops.EagerTensor

#### or the same with universal functions

In [16]:
tf.multiply(a,b).numpy()

10

In [17]:
type(tf.multiply(a,b))

tensorflow.python.framework.ops.EagerTensor

In [18]:
# It converts a tensor object into an numpy.ndarray object. 
# This implicitly means that the converted tensor will be now processed on the CPU.
type(tf.multiply(a,b).numpy())

numpy.int32

In [19]:
a_matrix = tf.constant([[1,2], [3,4]])
b_matrix = tf.constant([[5,6], [7,8]])
b_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8]])>

In [20]:
tf.matmul(a_matrix, b_matrix)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

#### Note, we cannot reassign values of constants (like we can with Variables).

In [21]:
print(a_matrix, b_matrix, sep="\n")

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


### 1.2 tf.Variable

<p>Variables are mutable and can be updated and reassigned new values. Variables are usually weights and biases of a model that are optimized during training, they also indicate the degrees of freedom of the model (what model parameters that can change, thus making the model flexible).</p>

In [22]:
var = tf.Variable(3.)
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [23]:
# Reassign the value of a Variable
var.assign(4)
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.0>

In [24]:
var.numpy()

4.0

In [25]:
# we can also create multi dim Variables.
d = tf.Variable(np.random.randn(3, 3)) #reshape
# automatically assings data type
d

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float64, numpy=
array([[ 0.30863391, -0.48344918,  1.94359728],
       [ 1.80880743, -0.78233433,  1.31210187],
       [-0.25535537,  1.39223562, -0.35847078]])>

In [26]:
# inplace increase / decrease Variable values

var.assign(10)
print('original value:', var.numpy())
print('add 1:', var.assign_add(1.).numpy())
print('subtract 5:', var.assign_sub(5.).numpy())

original value: 10.0
add 1: 11.0
subtract 5: 6.0


### Variables also have a lot of attributes associated with them

In [27]:
v = tf.Variable([[3.,3.2], [1.2,2.2]], dtype=tf.float32, name='my_variable')

print('name  : ', v.name)
print('type  : ', v.dtype)
print('shape : ', v.shape)
print('device: ', v.device)

name  :  my_variable:0
type  :  <dtype: 'float32'>
shape :  (2, 2)
device:  /job:localhost/replica:0/task:0/device:CPU:0


<center><img src="images/tf_to_np.png" /></center>

## 2. Operations / Ops

<p>Operations can be carried out directly or assigned to variables.</p>

In [28]:
op1 = tf.add(a,b)
op1

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [29]:
a+b # same as tf.add

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [30]:
v = a+b
u = v+2
w = v*u
z = w*3
z

<tf.Tensor: shape=(), dtype=int32, numpy=189>

### Look at the computational graph with @tf.function

<p>@tf.function is a very useful module that can be used to convert simple python functions into a highly optimized computational graph that can be run on any runtime environment. When we build a model and then train it TensorFlow we can compile the model and optimize the executions.</p>

In [31]:
@tf.function
def func2(a,b):
        z = tf.multiply(a,b, name='z')
        y1 = tf.constant(3, name='3')
        y2 = tf.constant(4)
        w1 = tf.add(z, y1, name='w1')
        w2 = tf.add(z, y2, name='w2')
        
        return(w1+w2)

In [32]:
func2(10, 20)

<tf.Tensor: shape=(), dtype=int32, numpy=407>

In [33]:
@tf.function
def func(a,b):
    with tf.name_scope('first'):
        z = tf.multiply(a,b, name='z')
    with tf.name_scope('second'):
        y1 = tf.constant(3, name='3')
        y2 = tf.constant(4)
        w1 = tf.add(z, y1, name='w1')
        w2 = tf.add(z, y2, name='w2')
        
    return(w1+w2)

In [34]:
# Setup a writer to save graph information and TensorFlow logs
# To be displayed with Tensorboard

writer = tf.summary.create_file_writer(logdir)
tf.summary.trace_on()

In [35]:
a = tf.constant(3)
b = tf.constant(4)
func(a,b)
with writer.as_default():
    tf.summary.trace_export(
        name="func2",
        step=0,
        profiler_outdir=logdir)

Instructions for updating:
use `tf.profiler.experimental.stop` instead.


In [36]:
logdir

'C:\\Users\\Dell\\tf_logs\\r20201225225922\\'

In [37]:
# %load_ext tensorboard

In [38]:
# run tensorboard in the shell
# !tensorboard --logdir='C:\\Users\\Dell\\tf_logs\\r20201225222503\\'
#!tensorboard --logdir $logdir

### tf.function and Conditional statements

<p>It is difficult to use conditions in graphs but we could implement that easily using @tf.function decorator</p>

In [39]:
@tf.function 
def g(x):
    y = tf.reduce_sum(x)
    if y > 0:
        return y
    return tf.abs(y)

In [40]:
# Returns the source code generated by AutoGraph, as a string.
print(tf.autograph.to_code(g.python_function))

def tf__g(x):
    with ag__.FunctionScope('g', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        y = ag__.converted_call(ag__.ld(tf).reduce_sum, (ag__.ld(x),), None, fscope)

        def get_state():
            return (retval_, do_return)

        def set_state(vars_):
            nonlocal retval_, do_return
            (retval_, do_return) = vars_

        def if_body():
            nonlocal retval_, do_return
            try:
                do_return = True
                retval_ = ag__.ld(y)
            except:
                do_return = False
                raise

        def else_body():
            nonlocal retval_, do_return
            try:
                do_return = True
                retval_ = ag__.converted_call(ag__.ld(tf).abs, (ag__.ld(y),), None, fscope)
            except:
                do_return 

## Calculate gradients

<p>Gradient evaluation is very important machine learning because it is based on function optimization. You can use tf.GradientTape() method to record the gradient of an arbitrary function
Like differentiation or slope</p>

In [41]:
w = tf.Variable(3.0)

# Gradient scope for the function w^2
with tf.GradientTape() as tape:
    expression = tf.exp(w) + 2 * w +  w * w

grad = tape.gradient(expression, w)
print(f'The gradient of exp at {w.numpy()} is {grad.numpy()}')

The gradient of exp at 3.0 is 28.08553695678711


### Gradient of the Sigmoid function

<p>In this example we evaluate the gradient of the sigmoid function</p>

<center><img src="images/first.png"/></center>

<p>Note that</p>

<center><img src="images/second.png"/></center>

<p>For instance</p>

<center><img src="images/third.png"/></center>

In [49]:
# Computes exponential of x element-wise.
def sigmoid(x):
    return 1/(1 + tf.exp(-x))

In [51]:
# Record operations for automatic differentiation.
#define a varaible
x = tf.Variable(0.)

#record the gradient
with tf.GradientTape() as tape:
    sig = sigmoid(x)
    
res = tape.gradient(sig, x).numpy()
print('The gradient of the sigmoid function at 0.0 is ', res)


The gradient of the sigmoid function at 0.0 is  0.25
