## Cleaning Data

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('./dataset/train.csv')

In [3]:
# Titanic dataset: Has dataset of all passengers that were on Titanic
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
# Output(y) is Survived column
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [5]:
# Our problem statement is: We have information of passenger given: We have to find whether passenger survived or not
# Two things to look into:
#      A.) Whether all columns are important or not (eg: name is not important, passemger id is not important)
                                                  # (eg: PClass: Higher class or lower class; mattered that time
                                                  # eg Gender and age important: children first, then women)
                                                  # (eg: Embarked:Location C = Cherbourg, Q = Queenstown, S = Southampton)

In [6]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
columns_to_drop = ['PassengerId','Name','Ticket', 'Cabin', 'Embarked']

In [8]:
# Can drop data column wise or row wise, axis=1 for column wise
clean_data = data.drop(columns_to_drop,axis=1)

In [9]:
clean_data.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0         0       3    male  22.0      1      0   7.2500
1         1       1  female  38.0      1      0  71.2833
2         1       3  female  26.0      0      0   7.9250
3         1       1  female  35.0      1      0  53.1000
4         0       3    male  35.0      0      0   8.0500

In [10]:
# Now, to convert text data to numbers
from sklearn.preprocessing import LabelEncoder

In [11]:
le = LabelEncoder()

In [12]:
clean_data["Sex"] = le.fit_transform(clean_data["Sex"])

In [13]:
# Male =1
# Female=0
clean_data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0         0       3    1  22.0      1      0   7.2500
1         1       1    0  38.0      1      0  71.2833
2         1       3    0  26.0      0      0   7.9250
3         1       1    0  35.0      1      0  53.1000
4         0       3    1  35.0      0      0   8.0500

In [14]:
# Notice: 891 people survived, had PClass, had gender but only 714 people had age
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int32  
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
dtypes: float64(2), int32(1), int64(4)
memory usage: 45.4 KB


In [15]:
# To solve age problem, we replace NA age with average age of available people
clean_data = clean_data.fillna(clean_data['Age'].mean())

In [16]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int32  
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
dtypes: float64(2), int32(1), int64(4)
memory usage: 45.4 KB


In [17]:
# Now, separate data into X and y
input_cols = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']
output_cols = ['Survived']

X = clean_data[input_cols]
y = clean_data[output_cols]

X.shape, y.shape

((891, 6), (891, 1))

In [18]:
X.head()

Pclass  Sex   Age  SibSp  Parch     Fare
0       3    1  22.0      1      0   7.2500
1       1    0  38.0      1      0  71.2833
2       3    0  26.0      0      0   7.9250
3       1    0  35.0      1      0  53.1000
4       3    1  35.0      0      0   8.0500

In [19]:
y.head()

Survived
0         0
1         1
2         1
3         1
4         0

## Entropy

In [20]:
# entropy of that column/feature
def entropy(col):
    # data is the number of unique classes
    # return_counts returns the number of times each unique item/class appears in 1d array
    data, counts = np.unique(col, return_counts=True)
    # Total number of items are also needed
    N = float(col.shape[0])
    
    ent = 0.0
    # Entropy = - Σ P log2 P
    # Now P = count/total count
    for count in counts:
        p = count / N
        ent += p * np.log2(p)
        
    return -ent

In [21]:
col = np.array([2,2,3,3,4,4,4])
entropy(col)

1.5566567074628228

In [22]:
# Entropy is one when there are equal number of elements of each class
col = np.array([2,2,2,3,3,3])
entropy(col)

1.0

In [23]:
# Entropy is zero when all elements are same i.e there is no randomness
col = np.array([4,4,4,4,4,4])
entropy(col)

-0.0

#### np.unique demonstration

In [24]:
data, counts = np.unique(clean_data['Survived'], return_counts=True)

In [25]:
data

array([0, 1], dtype=int64)

In [26]:
counts

array([549, 342], dtype=int64)

In [27]:
data, counts = np.unique([2,2,3,3,4,4,4], return_counts=True)

In [28]:
data

array([2, 3, 4])

In [29]:
counts

array([2, 2, 3], dtype=int64)

## Information Gain

In [30]:
def divide_data(x_data, fkey, fval):
# >>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
# ...                    columns=['a', 'b', 'c'])
# >>> df2
#    a  b  c
# 0  1  2  3
# 1  4  5  6
# 2  7  8  9
    # eg: Windy = True(1) or False(0); say fval=0.64
    #              Windy
    #             /   \
    #            /     \
    #         [ N ]    [ N ]
    #         [ N ]    [ N ]
    #         [ Y ]    [ Y ]        
    #         [ Y ]    [ Y ]
    #         [ N ]    [ N ]
    #         [ Y ]   
    # If >0.64, store the corresponding rows in x_right, Initially x_right is only column names, we will be adding rows later
    # If <0.64, store the corresponding rows in x_left,
    x_right = pd.DataFrame([], columns=x_data.columns)
    x_left = pd.DataFrame([], columns=x_data.columns)
    
    # Iterate through all the rows in the clean_data
    for xi in range(x_data.shape[0]):
        # Get column value of that feature for row=0,1,2,....
        # iloc is index based filtering
        val = x_data[fkey].iloc[xi]
        
        if val > fval:
            x_right = x_right.append(x_data.loc[xi])
        else:
            x_left = x_left.append(x_data.loc[xi])
        
    return x_left, x_right

In [31]:
# We are making a binary tree, hence split node into 2
# x_data = clean_data = X+y
# If a person will buy ps5 or not. Lets say split this across salaries. fkey = Salaries. (feature)
# We need a a value to split the node: say you want to split like salary < 10 lac (left child) & sal > 10 lac (right child): fval = 10
                                    # another eg: Gender = 0(Female) or 1(Male). The mean of gender column may be 0.64 which implies more male
                                    # members
def information_gain(x_data,  fkey, fval):
    left, right = divide_data(x_data, fkey, fval)
    
    # % of examples in left and right
    # l = total number of examples in left/ total number of examples
    l = float(left.shape[0]) / x_data.shape[0]
    r = float(right.shape[0]) / x_data.shape[0]
    
    hs = entropy(x_data.Survived)
    
    # igain = H(s) - new entropy 
    igain = hs - (l * entropy(left.Survived) + r * entropy(right.Survived))
    return igain

In [32]:
for f in X.columns: 
    # print column/feature name
    print(f)
    # clean_data = Entire data including X and y
    # f = column/feature name = fkey
    # clean_data[f].mean() : mean value of the f column = fvalue
    print(information_gain(clean_data, f, clean_data[f].mean()))

Pclass
0.07579362743608165
Sex
0.2176601066606142
Age
0.001158644038169343
SibSp
0.009584541813400071
Parch
0.015380754493137694
Fare
0.042140692838995464


In [33]:
# From the values obtained above, we can Sex is the most important factor for survival.
# So it becomes root node

#### Demonstration of terms used above

In [34]:
X.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [35]:
clean_data

Survived  Pclass  Sex        Age  SibSp  Parch     Fare
0           0       3    1  22.000000      1      0   7.2500
1           1       1    0  38.000000      1      0  71.2833
2           1       3    0  26.000000      0      0   7.9250
3           1       1    0  35.000000      1      0  53.1000
4           0       3    1  35.000000      0      0   8.0500
..        ...     ...  ...        ...    ...    ...      ...
886         0       2    1  27.000000      0      0  13.0000
887         1       1    0  19.000000      0      0  30.0000
888         0       3    0  29.699118      1      2  23.4500
889         1       1    1  26.000000      0      0  30.0000
890         0       3    1  32.000000      0      0   7.7500

[891 rows x 7 columns]

In [36]:
clean_data['Age'].mean()

29.699117647058763

In [37]:
x_right = pd.DataFrame([], columns=clean_data.columns)

In [38]:
x_right

Empty DataFrame
Columns: [Survived, Pclass, Sex, Age, SibSp, Parch, Fare]
Index: []

In [39]:
x_right.shape

(0, 7)

In [40]:
clean_data.shape[0]

891

In [41]:
x_right = x_right.append(clean_data.loc[0])

In [42]:
x_right

Survived  Pclass  Sex   Age  SibSp  Parch  Fare
0       0.0     3.0  1.0  22.0    1.0    0.0  7.25

## Decision Tree using sklearn

In [43]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [44]:
# Criterion: The algorithm to be used: 1) Gini based indexing 2) Entropy and information gain based 
# Max_depth: The maximum depth of the tree. If None, then nodes are expanded until all leaves are pure
dt_tree = DecisionTreeClassifier(criterion='entropy',max_depth=5)

In [45]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [46]:
dt_tree.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [47]:
dt_tree.score(X_test,y_test)

0.8101694915254237

In [48]:
dt_tree.predict(X_test[:10])

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1], dtype=int64)

In [49]:
y_test[:10]

Survived
709         1
439         0
840         0
720         1
39          1
290         1
300         1
333         0
208         1
136         1

## Custom Decision Tree

In [50]:
class DecisionTree:
    def __init__(self, depth=0, max_depth=5):
        self.left = None
        self.right = None
        self.fkey = None
        self.fval = None
        self.max_depth = max_depth
        self.depth = depth
        self.target = None # what i'm going to predict at a particular Node, say leaf node has 50 examples (40 Y and 10 N), 
                           # then target of this leaf node is Y (80% accuracy)
            
    def fit(self, X_train):
        features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']
        # We are going to calculate information gain for each of these features
        # and whichever has maximum information gain goes into node 
        info_gains = []
        
        for ix in features:
            i_gain = information_gain(X_train, ix, X_train[ix].mean())
            info_gains.append(i_gain)
        
        # np.argmax returns index of maximum value
        # features[np.argmax] returns  the actual feature
        self.fkey = features[np.argmax(info_gains)]
        self.fval = X_train[self.fkey].mean()
        print("Making tree feature is ", self.fkey)
        
        # Create the tree
        # split the data
        data_left, data_right = divide_data(X_train, self.fkey, self.fval)
        # reset_index will reset the index again from starting for each subpart
        data_left = data_left.reset_index(drop=True)
        data_right = data_right.reset_index(drop=True)
        
        # I have to stop when i have reached the leaf node or when I have reached the max depth
        
        # Truly a left/right node
        # Splitting data not possible
        if data_left.shape[0]  == 0 or data_right.shape[0] ==0:
            if X_train.Survived.mean() >= 0.5:
                self.target = "Survive"
            else:
                self.target = "Dead"
            return
        
        #Stop earyly when depth >=max depth
        if(self.depth>=self.max_depth):
            if X_train.Survived.mean() >= 0.5:
                self.target = "Survive"
            else:
                self.target = "Dead"
            return
        
        # Recursive Case
        self.left = DecisionTree(depth=self.depth + 1)
        self.left.fit(data_left)
        
        self.right = DecisionTree(depth=self.depth + 1)
        self.right.fit(data_right)
        
                #You can set the target at every node
        if X_train.Survived.mean() >= 0.5:
            self.target = "Survive"
        else:
            self.target = "Dead"
        return
    
    def predict(self,test):
        if test[self.fkey]>self.fval:
            #go to right
            if self.right is None:
                return self.target
            return self.right.predict(test)
        else:
            if self.left is None:
                return self.target
            return self.left.predict(test)

#### Train-Validation-Test Set Split

In [51]:
dt = DecisionTree()

In [52]:
# split basically does same thing as train_test_split
split = int(0.7*clean_data.shape[0])
# take 70% of data as training data
train_data = clean_data[:split]
# remaining 30% as test data
test_data = clean_data[split:]
# To understand working of reset_index https://datatofish.com/reset-index-pandas-dataframe/
test_data = test_data.reset_index(drop=True)

In [53]:
train_data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0         0       3    1  22.0      1      0   7.2500
1         1       1    0  38.0      1      0  71.2833
2         1       3    0  26.0      0      0   7.9250
3         1       1    0  35.0      1      0  53.1000
4         0       3    1  35.0      0      0   8.0500

In [ ]:
dt.fit(train_data)

Making tree feature is  Sex
Making tree feature is  Pclass
Making tree feature is  Age
Making tree feature is  SibSp
Making tree feature is  Pclass
Making tree feature is  Pclass
Making tree feature is  Age
Making tree feature is  SibSp
Making tree feature is  Parch
Making tree feature is  Pclass
Making tree feature is  SibSp
Making tree feature is  Fare
Making tree feature is  Parch
Making tree feature is  Pclass
Making tree feature is  Pclass
Making tree feature is  Pclass
Making tree feature is  Pclass
Making tree feature is  Parch
Making tree feature is  SibSp
Making tree feature is  Fare
Making tree feature is  Age
Making tree feature is  Age
Making tree feature is  Fare
Making tree feature is  Age
Making tree feature is  Age
Making tree feature is  Fare
Making tree feature is  Age
Making tree feature is  Parch
Making tree feature is  Fare
Making tree feature is  Fare
Making tree feature is  Fare
Making tree feature is  Pclass
Making tree feature is  Fare
Making tree feature is  P

In [ ]:
y_pred = []
for i in range(test_data.shape[0]):
    y_pred.append(dt.predict(test_data.loc[i]))

In [ ]:
y_pred[:10]

In [ ]:
print(dt.fkey)
print(dt.fval)
print(dt.left.fkey)
print(dt.right.fkey)

In [ ]:
y_actual = test_data[output_cols]

In [ ]:
y_actual[:10]

In [ ]:
le = LabelEncoder()
y_pred = le.fit_transform(y_pred)

In [ ]:
print(y_pred)

In [ ]:
y_pred = np.array(y_pred).reshape((-1,1))
print(y_pred.shape)

In [ ]:
acc = np.sum(y_pred==y_actual)/y_pred.shape[0]

In [ ]:
acc = np.sum(np.array(y_pred)==np.array(y_actual))/y_pred.shape[0]

In [ ]:
print(acc)

## Decision Tree Visualization

In [ ]:
import pydotplus
from six import StringIO # data format
from IPython.display import Image
from sklearn.tree import export_graphviz
import graphviz    

In [ ]:
dot_data = StringIO()
export_graphviz(dt_tree, out_file=dot_data, filled=True, rounded=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())